### ISSUE TITLE
Editor crashes with fatal error regularly, while in-game & in-editor

### ISSUE THREAD

**Issue by Vicky-mSocial** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#54] opened 2022-10-30 15:16 UTC
I attached the log file.
I am using this plugin for a basic screen share and join channel. just copied nodes from your blueprint project.
I am also using plugin as is, did do any modifications
[AgoraBPExample.log](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9896146/AgoraBPExample.log)

**Comment by oneSitDown** [comment] 2022-10-31 02:24
![image](https://user-images.githubusercontent.com/47908151/198918143-54a1d12f-517e-4ee5-b533-56f3f0280269.png)
This seems to be the problem here, you can try to modify it and see if it can be reproduced.

**Comment by Vicky-mSocial** [comment] 2022-10-31 03:58
It lasted for little long then crashed again, these are logs and crash dumps
[mSocial_UE5.log](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9897924/mSocial_UE5.log)
[Crashes.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9897926/Crashes.zip)

**Comment by oneSitDown** [comment] 2022-10-31 16:12
Can you tell me the probability and interval of crashes?

**Comment by Vicky-mSocial** [comment] 2022-11-01 05:27
I think it might be because of testing multiple users on same computer. Currently testing it on different computers, if I dont see a crash I will close this issue

**Comment by Vicky-mSocial** [comment] 2022-11-04 06:06
It started crashing a lot while play testing in editor even with single player, I am using unreal from source build v5.0.3 currently. Crashes are too often every time I hit play & enter a trigger to start screen sharing it crashes, sometimes it crashes after 10sec of leaving PIE. I don't see these crashes happening in packaged game only happens while in editor and it's hard to test out features because of it

**Comment by oneSitDown** [comment] 2022-11-04 12:30
Are you urgent about this issue? We will fix it in the next release. The next version may be released around the end of this month. I think it might be a threading issue. You can refer me to fix it like this.
[AgoraCode.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9938200/AgoraCode.zip)

**Comment by Vicky-mSocial** [comment] 2022-11-05 09:50
crashes are too frequent when I used a 3D widget with a Two-sided material on image. (if you want to debug). We are looking for a solution as fast as possible as it has been used for a key feature. Will try out your code and see if it works

**Comment by oneSitDown** [comment] 2022-11-05 09:53
I have copied the corresponding code to the above answer, you can try to replace the corresponding file under the zip package.

**Comment by oneSitDown** [comment] 2022-11-05 09:54
> Are you urgent about this issue? We will fix it in the next release. The next version may be released around the end of this month. I think it might be a threading issue. You can refer me to fix it like this. [AgoraCode.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9938200/AgoraCode.zip)

this zip file

**Comment by Vicky-mSocial** [comment] 2022-11-05 10:20
i am using the blueprint plugin

**Comment by oneSitDown** [comment] 2022-11-05 10:22
> i am using the blueprint plugin

The next version of blueprint and cpp will be merged into one sdk

**Closed** 2022-11-05 17:43 UTC

**Comment by playamigos** [comment] 2023-07-26 20:23
I faced this issue because I have created multiple agora engine instances in a single game session. Keep it to just one AgoraEngine instance per game session to avoid crashes.
