### ISSUE TITLE
Mute Microphone 

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#55] opened 2022-11-01 17:06 UTC
Hello and sorry for asking this again.
Is juts that I could not find something to close your microphone apart from those methods about the steam, but I don't want to mute the stream, just your own audio. I'm usign your "Join Channel Audio" system.

I see that I can set the volume using the class "device manager", do you think that this would be the best option?

**Comment by oneSitDown** [comment] 2022-11-01 17:26
are you try "muteLocalAudioStream"?

**Comment by Shumaro211** [comment] 2022-11-01 17:42
oh wait is not that for the share stream or is also for normal voice channels?
I tried to use one of those functions, but it was crashing, I'd try again if that's what I'm looking for.

**Comment by icywind** [comment] 2022-11-02 01:11
muteLocalAudioStream works for any stream that you publish to the channel.

**Comment by Shumaro211** [comment] 2022-11-02 01:15
just to make sure when we say "stream" are we talking about any kind of voice connection or just for the screen share stream?

**Comment by oneSitDown** [comment] 2022-11-02 02:08
![image](https://user-images.githubusercontent.com/47908151/199378282-814a948a-0fb0-4ba9-9bda-c38703110de9.png)
are you try this code？

**Comment by oneSitDown** [comment] 2022-11-02 16:05
this also can use in joinchannel，you can see joinchannel api have option too.

**Comment by oneSitDown** [comment] 2022-11-03 03:54
https://api-ref.agora.io/en/video-sdk/cpp/4.x/API/class_irtcengine.html#api_irtcengine_mutelocalaudiostream

**Comment by Shumaro211** [comment] 2022-11-04 15:01
I created a function in the audio widget class to call the Rtc function "muteLocalAudioStream", calling this first function is working but is not doing anything, is this way the right way?

![image](https://user-images.githubusercontent.com/66711189/200006866-6dc1122a-b6c3-4bad-b5a9-ed566eb283e1.png)

**Comment by oneSitDown** [comment] 2022-11-04 15:04
I think that's right. If the problem is solved, can you close the issue?

**Comment by Shumaro211** [comment] 2022-11-04 15:22
Is not, is not doing anything, but I don't see the logic to mute the audio in this function apart from that if
![image](https://user-images.githubusercontent.com/66711189/200011659-a5427014-e538-4e84-91db-a0ebf8603d2f.png)

**Comment by Shumaro211** [comment] 2022-11-04 15:23
ohh sorry, the value has to be true, is working

**Closed** 2022-11-04 16:52 UTC
